# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02b2ca21898574ac2feb0f483b46c8cef89c65b63a05187eca5a5318c68af073003f3e5ca9fc80fbbc6d653cf27e0da6c453cac55b68e745636c3ae722a2a76c

test:
  secret_key_base: 386988aa33a0f3895a2b32d215102ed030fdbce72e22997cacb8108702467616503c9dc0c3bdf0676775f50ef4a244b5e03bc10b8cb183400f021e8496a1da4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
